### ISSUE TITLE
Help for basler tof installation

### ISSUE THREAD

**Issue by Opros87** [uos/basler_tof#3]
Hello,

I am a beginner in using ROS.
I am trying to install the basler_tof pack to acquire data with my basler tof camera.

I followed the instructions given in the readme file but when I write the instruction
roslaunch basler_tof basler_tof.launch

I get the error message below
[basler_tof.launch] is neither a launch file in package [basler_tof] nor is [basler_tof] a launch file name
The traceback for the exception was written to the log file

I do not understand this error since the launch file actually exists.

Thanks a lot in advance for your help
Best regards
Roberto

**Comment by mintar** [comment]
Did you source your `setup.bash`? So for example, if your catkin workspace is at `~/catkin_ws`, type:

```bash
source ~/catkin_ws/devel/setup.bash
```

You can also put this line at the end of your `~/.bashrc` file, so that it is executed whenever you open a new terminal.

**Comment by Opros87** [comment]
Hi thanks for your answer.

Now the node starts but the camera is not found although I created an ethernet connection.

**Comment by mintar** [comment]
Does the viewer application from Basler work? `/opt/BaslerToF/bin/PylonViewerApp`

**Comment by Opros87** [comment]
The viewer application opens but even there no camera is recognized.

**Comment by mintar** [comment]
Then please fix the problem there first. Once the camera works in PylonViewerApp, it should also work with this driver. This doesn't seem to be a problem with the ROS driver.

**Comment by Opros87** [comment]
Problem solved.
Thanks for your help!

**Comment by mintar** [comment]
Glad to be of help!
