### ISSUE TITLE
I can't find dynamic_reconfigure  package.

### ISSUE THREAD

**Issue by spy14414** [uos/basler_tof#6]
Hello,I  can't find your dynamic_reconfigure  package.When I browse this page, I get 404.

**Comment by mintar** [comment]
Which URL?

**Comment by spy14414** [comment]
https://github.com/uos/basler_tof/blob/indigo/dynamic_reconfigure
QAQ

**Comment by mintar** [comment]
Why do you believe this URL should exist? Also, what does QAQ mean? If you are looking for help, please spend more effort to make your request easy to read and understand.

**Comment by spy14414** [comment]
You wrote this URL  in the readme document. 
   Dynamically Reconfigurable Parameters
      See the dynamic_reconfigure package for details on dynamically reconfigurable parameters.
      ~frame_rate (int, default: 15)
          Acquisition rate at which the frames are captured. [Hz] Range: 1 to 15
Maybe this URL is private. Actually I don’t  really need it.
 QAQ means “ I‘m crying " in  China. Don't you think Q  likes a tearful eye?

**Comment by spy14414** [comment]
Sorry for my late reply.

**Comment by mintar** [comment]
Ah, I get you. I'll update the README. Thank you for reporting this issue! :)
