### ISSUE TITLE
ConsumerImplHelper/ToFCamera.h

### ISSUE THREAD

**Issue by etienne72230** [uos/basler_tof#8]
Hello,
I want to use basler_tof whith ROS kinetic on a Raspberry model 3 and Raspbian but I have an error at the compilation.
The file ToFCamera.h can't be find :
` fatal error: ConsumerImplHelper/ToFCamera.h`

I have download the librairy from this link : https://www.baslerweb.com/de/vertrieb-support/downloads/downloads-software/tof-software-linux-64-bit/ and past the folder BaslerToF to /opt 
But the folder not include the file ToFCamera.h

Can you help me ?

Thanks you for your attention.

**Comment by mintar** [comment]
As far as I can see, the Basler library is only available for x86 processors, not ARM processors like the Raspi. So unfortunately that won't work.

**Comment by etienne72230** [comment]
Pylon is compatible with ARM processors but i can't find the ConsumerImplHelper : https://www.baslerweb.com/en/sales-support/downloads/software-downloads/pylon-5-2-0-linux-arm-32-bit-hardfloat/

**Comment by mintar** [comment]
The standard Pylon library doesn't work with the Basler ToF cameras. The Basler ToF software is here:

https://www.baslerweb.com/en/sales-support/downloads/software-downloads/#type=tofsoftware;language=all;version=all

That page only lists Linux 32 bit (x86), Linux 64 bit (x86_64) and Windows; no ARM unfortunately. :(

If you need ARM compatibility, you could ask Basler support if they plan to compile their library for ARM. Until then, I'm afraid there's nothing I can do.
